### ISSUE TITLE
Running both the server and client from .exe causes client to crash

### ISSUE THREAD

**Issue by bradleywolinski** [procro04/clue-less#22]
1. Run server from ...\Clue-Less\Clue-Less-Server\bin\Debug\net6.0\Clue-Less-Server.exe
2. Run game from ...\Clue-Less\Clue-Less\bin\Debug\net6.0\Clue-Less.exe
3. Enter username and select character
4. Observe game crash

Is this expected behavior? Or is there any reason behind it?

**Comment by icanhearyousmile** [comment]
Copy and paste the batch file that I've placed into the shared OneDrive -> EN.605.601.83 folder (LaunchServer.bat) into the file that contains your server executable (\Clue-Less\Clue-Less-Server\bin\Debug\net6Copy and paste the attached batch file into the file that contains your server executable (\Clue-Less\Clue-Less-Server\bin\Debug\net6.0\Clue-Less-Server.exe); Double click "LaunchServer.bat" and it will run the server locally on your machine. Then you should be able to run the game client and play normally. .0\Clue-Less-Server.exe); Double click "LaunchServer.bat" and it will run the server locally on your machine. Then you should be able to run the game client and play normally.
